site_name: Diario de aula
site_url: https://garmarcj.github.io/DAM-DIARIO-20262027/
site_author: Cristian Garcia
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: red
  features:
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
nav:
  - Inicio: index.md
  - Dia 1: diario001.md
  - Día 2: diario002.md
  - Día 3: diario003.md
  - Dia 4: diario004.md
  - Día 5: diario005.md
  - Día 6: diario006.md
  - Día 7: diario007.md
  - Día 8: diario008.md
  - Día 9: diario009.md
  - Día 10: diario010.md
  - Día 11: diario011.md
  - Día 12: diario012.md
  - Día 13: diario013.md
  - Día 14: diario014.md
  - Día 15: diario015.md
  - Día 16: diario016.md
  - Día 17: diario017.md
  - Día 18: diario018.md
  - Día 19: diario019.md
  - Día 20: diario020.md
  - Día 21: diario021.md
  - Día 22: diario022.md
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
plugins:
  - with-pdf:
      output_path: pdf/diariodeaula.pdf
      cover: true
      toc_title: "diario de aula"
      exclude_pages:
        - licencia.md
